apiVersion: v1
kind: Service
metadata:
  name: image-recognition-service
spec:
  selector:
    app: image-recognition-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
